# Generated by Django 6.0.2 on 2026-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_category_event_category_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
