# Generated by Django 6.0.2 on 2026-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
